"""initial schema: concept-graph knowledge base

Hand-authored (not autogenerated): autogenerate cannot emit ``CREATE EXTENSION
vector``, the HNSW indexes (``vector_cosine_ops`` opclass), or the functional
unique index ``concepts(workspace_id, lower(name))``. Vector columns are
``vector(1536)`` to match ``app.models.EMBED_DIM`` (text-embedding-3-small).

Revision ID: 0001
Revises:
Create Date: 2026-06-18
"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBED_DIM = 1536  # keep in sync with app.models.EMBED_DIM


def upgrade() -> None:
    # pgvector must exist before any vector-typed column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    # Exactly one personal (private) workspace per user.
    op.execute(
        "CREATE UNIQUE INDEX uq_workspaces_owner_private "
        "ON workspaces (owner_id) WHERE type = 'private'"
    )

    op.create_table(
        "workspace_members",
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("user_id", sa.String(), primary_key=True),
        sa.Column("role", sa.String(), nullable=False),
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")),
    )
    op.create_index("ix_documents_workspace_status", "documents", ["workspace_id", "status"])

    op.create_table(
        "clusters",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=True),
    )
    op.create_index("ix_clusters_workspace", "clusters", ["workspace_id"])

    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "document_id",
            sa.Uuid(),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("embedding", Vector(EMBED_DIM), nullable=True),
        sa.UniqueConstraint("document_id", "content_hash", name="uq_chunks_document_hash"),
    )
    op.create_index("ix_chunks_document", "chunks", ["document_id"])
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.create_table(
        "concepts",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("canonical", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", Vector(EMBED_DIM), nullable=True),
        sa.Column(
            "cluster_id",
            sa.Uuid(),
            sa.ForeignKey("clusters.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index("ix_concepts_workspace", "concepts", ["workspace_id"])
    op.create_index("ix_concepts_cluster", "concepts", ["cluster_id"])
    # Case-insensitive uniqueness = the merge/dedup race backstop.
    op.execute(
        "CREATE UNIQUE INDEX uq_concepts_workspace_lower_name "
        "ON concepts (workspace_id, lower(name))"
    )
    op.execute(
        "CREATE INDEX ix_concepts_embedding_hnsw ON concepts "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.create_table(
        "concept_aliases",
        sa.Column(
            "concept_id",
            sa.Uuid(),
            sa.ForeignKey("concepts.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("alias", sa.String(), primary_key=True),
    )

    op.create_table(
        "concept_mentions",
        sa.Column(
            "concept_id",
            sa.Uuid(),
            sa.ForeignKey("concepts.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "chunk_id",
            sa.Uuid(),
            sa.ForeignKey("chunks.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "document_id",
            sa.Uuid(),
            sa.ForeignKey("documents.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )
    op.create_index("ix_concept_mentions_document", "concept_mentions", ["document_id"])

    op.create_table(
        "edges",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "source_concept_id",
            sa.Uuid(),
            sa.ForeignKey("concepts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "target_concept_id",
            sa.Uuid(),
            sa.ForeignKey("concepts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.UniqueConstraint(
            "workspace_id",
            "source_concept_id",
            "target_concept_id",
            "relation",
            name="uq_edges_triple",
        ),
    )
    op.create_index("ix_edges_workspace", "edges", ["workspace_id"])
    op.create_index("ix_edges_endpoints", "edges", ["source_concept_id", "target_concept_id"])


def downgrade() -> None:
    # Reverse FK order. Indexes drop with their tables.
    op.drop_table("edges")
    op.drop_table("concept_mentions")
    op.drop_table("concept_aliases")
    op.drop_table("concepts")
    op.drop_table("chunks")
    op.drop_table("clusters")
    op.drop_table("documents")
    op.drop_table("workspace_members")
    op.drop_table("workspaces")
    # Leave the `vector` extension in place — it may be shared by other schemas.
    # op.execute("DROP EXTENSION IF EXISTS vector")
