"""M1 collaboration: workspace metadata, concept origin, workspace_invites

Adds project metadata to ``workspaces`` (``name`` + ``updated_at`` for the
dashboard), an ``origin`` discriminator to ``concepts`` (pipeline-extracted vs
hand-authored direction nodes), and the ``workspace_invites`` table (invite a
mentor by email before they have an account; bind their Cognito sub on accept).

Hand-authored to match 0001's functional/partial-index conventions (the unique
token index and the "one pending invite per (workspace, lower(email))" partial
index can't be autogenerated). Column adds carry a ``server_default`` so the
ALTERs backfill existing rows and cover the worker's Core INSERTs.

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-20
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- workspaces: project metadata for the dashboard ---
    op.add_column("workspaces", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "workspaces",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- concepts: distinguish pipeline-extracted from hand-authored nodes ---
    op.add_column(
        "concepts",
        sa.Column(
            "origin",
            sa.String(),
            nullable=False,
            server_default=sa.text("'extracted'"),
        ),
    )

    # --- workspace_invites: invite-before-account, keyed by email ---
    op.create_table(
        "workspace_invites",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "workspace_id",
            sa.Uuid(),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("invited_by", sa.String(), nullable=False),
        sa.Column(
            "status", sa.String(), nullable=False, server_default=sa.text("'pending'")
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.String(), nullable=True),
    )
    op.create_index(
        "ix_workspace_invites_workspace", "workspace_invites", ["workspace_id"]
    )
    op.execute("CREATE UNIQUE INDEX uq_invites_token ON workspace_invites (token)")
    # One live (pending) invite per email per workspace; case-insensitive email.
    op.execute(
        "CREATE UNIQUE INDEX uq_invites_ws_email_pending "
        "ON workspace_invites (workspace_id, lower(email)) WHERE status = 'pending'"
    )


def downgrade() -> None:
    # Reverse order; indexes drop with their table.
    op.drop_table("workspace_invites")
    op.drop_column("concepts", "origin")
    op.drop_column("workspaces", "updated_at")
    op.drop_column("workspaces", "name")
